### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by relative** [Arsenite33/Token-login#1]
ur really to olazsy to go to https://discord.com/%% and put ur token in localstorage wow cringe

**Comment by verticalsync** [comment]
wow cringe, extension is faster smh

**Comment by relative** [comment]
> wow cringe, extension is faster smh

extensions not faster if you have more than half a brain sorry bro

**Comment by verticalsync** [comment]
> > wow cringe, extension is faster smh
> 
> extensions not faster if you have more than half a brain sorry bro

Typing in a url and pasting a token is faster rather than going to %% opening dev console going to application and then setting token and refreshing

**Comment by ghost** [comment]
> > > wow cringe, extension is faster smh
> > 
> > 
> > extensions not faster if you have more than half a brain sorry bro
> 
> Typing in a url and pasting a token is faster rather than going to %% opening dev console going to application and then setting token and refreshing

if u have a brain its not hard plz just get a fucking brain

**Comment by relative** [comment]
yea
